# 阶段 1: 拉取源码并构建前端静态文件
FROM node:lts-alpine AS builder

WORKDIR /app

# 复制本地源码到容器中
COPY ./ACL4SSR-web .

# 安装依赖并打包
RUN npm install && \
    npm run build

# 阶段 2: 使用 Nginx 部署静态文件
FROM nginx:alpine

# 将第一阶段构建产物复制到 Nginx 的默认静态资源目录
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]